### ISSUE TITLE
Playing RomHacks on SD card 

### ISSUE THREAD

**Issue by Smith-and-einstein** [budude2/openfpga-GBC#66]
Hi, im looking for playing RomHacks on my SD card with Retropatcher but i can't find the right rom to patch, i only found Pokemon Red ++
Do i have to buy everdrive X5 or everdrive X7 for playing every Pokemon romhacks like Pokemon Prism/ Brown or Super gold 97 etc... ?
Thanks fpr your support.

**Comment by gLobbob0t** [comment]
This is not a rom download support page. Please look elsewhere. Btw: retropatcher is different from this core, this is not a issue of this core.

**Comment by Smith-and-einstein** [comment]
Im talking about the analog pocket* i forgot to mention it sorry

**Comment by gLobbob0t** [comment]
I know that we are talking about the Pocket, but Retropatcher has nothing to do with this core. The patcher is for converting .gb/c rom to .pocket files.
This core only works with .gb/c roms or romhacks. And since you asked about where to get the right rom this is not the place for this.

Please correct me when I misunderstood you.

**Comment by Smith-and-einstein** [comment]
No i don't demande rom i demande how it work with .pocket and .gb/c rom with everdrive

**Comment by gLobbob0t** [comment]
Doesn't work with .pocket files. This is not the support for Everdrive carts.

.pocket files work with the Pocket natively, you don't need this core for .pocket files.

This is a core. Think of it as a "emulator" for the pocket. With this you don't need a Everdrive or .pocket files. This core can run gb/c rom from the micro sd card. If you want to know how, look at the page for this core.

Btw: you can't demand anything on here. This should be closed since it seems like this has nothing to do with the core.

**Comment by Smith-and-einstein** [comment]
Alr thanks you for all
